# Generated by Django 5.1.4 on 2025-08-18 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organiser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('partner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('partner_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('player_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('partner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('partner_2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('partner_2_number', models.CharField(blank=True, max_length=15, null=True)),
                ('partner_2_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phonepay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(default='Pending', max_length=20)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('referred_by', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='organiser.tournamentcategory')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='organiser.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('txn_id', models.CharField(blank=True, max_length=100, null=True)),
                ('txn_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=20)),
                ('response_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='organiser.tournament')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='registration.tournamentregistration')),
            ],
        ),
    ]
